### PR TITLE
Upgrade to dotnet 6.0

### PR DESCRIPTION
**Pull request by micheleissa**
- Upgrade project to .NET 6.0
- Used new app template with top-level statements.
- Used global using directive.
- Used some C# 10 features.
- Upgraded NuGet packages to latest stable version.
- Refactored some code like delegates.
- Moved MessageValue to its own cs file.
- Modified env.json to connect to 172.0.0.1
-  Modified README file to reflect changes in code.

### CODE REVIEW

**Comment by micheleissa** [comment]
I have tested the code on a windows machine and a MacBook Pro one, the MQ was running as a container and I tried all scenarios successfully except Req/Res which keeps failing on me but even with original code so it might be issue with my setup.

**Comment by chughts** [comment]
Re Req/Rep - we usually find that issues are related to insufficient read permissions on the model queue. The model queue is used as a template for temporary reply queues. 


One code review comment that I have received relates to `ibmmq_samples.csproj`. The package reference to the nuget package specifies a hard version. ie. 
 
````
<PackageReference Include="IBMXMSDotnetClient" Version="9.3.0.1" />
````
 
Did you try by setting “Version=”*”” attribute from the above code? If that works then we are protected from bump releases of the client.

**Comment by micheleissa** [comment]
@chughts I find usage of `Version="*"` is a bit tricky becuase code will always use latest package which might introduce a breaking change so I find the explicit version is far better approach. What are your thoughts on that concern?

**Comment by chughts** [comment]
@RamSubbarao thoughts?

**Comment by ramsubbaraoc** [comment]
We don't expect a breaking change in normal circumstances. Being on the latest will ensure that known product issues are fixed.

**Review by ramsubbaraoc — APPROVED** [review]

**Review by RamSubbarao — APPROVED** [review]

**Pull request merged**
