### PR TITLE
Fix connection mode

### PR DESCRIPTION
**Pull request by micheleissa**
Based on conversation on #19 
- Add ```.gitignore``` file inside dotnet folder so all Visual Studio related should be ignored files will be ignored.
- Make the connection mode always managed.

### CODE REVIEW

**Comment by micheleissa** [comment]
I think the unmanaged client should be configuration driven not assumed, also according to [documentation ](https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.msc.doc/xms_unmanaged.htm)and what I understand from it SSL so I'm confused why the original lines were written that way.
I might be missing something so what do you propose the fix should be?

Thanks

**Comment by chughts** [comment]
The existing logic is deciding on whether it is running in managed or unmanaged based on whether TLS is needed for the connection. If TLS is needed and it's managed then `XMSC.WMQ_SSL_KEY_REPOSITORY` should be set to either `*SYSTEM` or `*USER`. 

So I am guessing that although you are running managed you are not running TLS is that correct?

**Comment by micheleissa** [comment]
> The existing logic is deciding on whether it is running in managed or unmanaged based on whether TLS is needed for the connection. If TLS is needed and it's managed then `XMSC.WMQ_SSL_KEY_REPOSITORY` should be set to either `*SYSTEM` or `*USER`.
> 
> So I am guessing that although you are running managed you are not running TLS is that correct?

Yes, correct I'm not running  TLS but I'm planning to test it later on.

**Comment by chughts** [comment]
So it that case we need another mechanism of working out if its managed or unmanaged.

**Comment by micheleissa** [comment]
I'm open for suggestions.

**Comment by micheleissa** [comment]
> I have been thinking about this, and unfortunately the only way I can see is by adding a new setting to `Env.ConnVariables`, eg. `is_managed`. It can default to `true` if missing. So the only way to force the logic though the unmanaged route would be to add the setting and set it to `false`.

Ok I will change the PR accordingly

**Comment by chughts** [comment]
Many thanks. While you are there, could you also update the pre-reqs to pull the IBMXMSDotnetClient.dll from nugget.

**Comment by micheleissa** [comment]
@chughts  You read my mind 👍 I was gonna ask you about that.

**Pull request merged**
